In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
embeddings = pd.read_csv('./data/graph.emd', sep=' ', header=None)

In [17]:
from sklearn.cluster import KMeans


X = embeddings.loc[:, 1:].values
kmeans = KMeans(n_clusters=3, random_state=10, max_iter=50).fit(X)

kmeans.labels_

array([2, 0, 1, 1, 0, 1, 0, 2, 0], dtype=int32)

In [13]:
embeddings[0].values

array([8, 7, 4, 1, 5, 3, 9, 2, 6])

In [19]:
from sklearn.cluster import AffinityPropagation


X = embeddings.loc[:, 1:].values
affinityprop = AffinityPropagation(max_iter=50).fit(X)

affinityprop.labels_

array([2, 0, 1, 2, 0, 1, 1, 2, 0])